var blankRequest = {
    title: new String,
    firstName: new String,
    lastName: new String,
    dateOfBirth: new Date,
    gender: new String,
    maritalStatus: new String,
    ssid: new String,
    occupation:new String,
    licenceNumber:new String,
    yearsHeld:new Number,
    fid: new String,
    city: new String,
    state: new String,
    zip: new String,
    phone: new String,
    email: new String,
    previousAddress: new String,
    carMake: new String,
    carModel: new String,
    carYear: new String,
    carMiles: new String,
    primaryUse: new String,
    ownOrLease: new String,
    lengthOfOwnership: new String,
    cover: new Array,
    previousAccidents: new String,
    accidentWithinFiveYears: new Boolean    
};

